import java.text.SimpleDateFormat

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'org.thecosmicfrog.luasataglance'

    compileSdk = 37

    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    defaultConfig {
        applicationId "org.thecosmicfrog.luasataglance"
        minSdk 29
        targetSdk 37
        versionCode generateVersionCode()
        versionName generateVersionName()
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    buildTypes {
        debug {
            resValue "string", "version_code", generateVersionCode().toString()
            resValue "string", "version_name", generateVersionName()
            resValue "string", "release_date", generateReleaseDate()

            applicationIdSuffix ".debug"
            debuggable true
        }
        release {
            resValue "string", "version_name", generateVersionName()
            resValue "string", "release_date", generateReleaseDate()

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions "api"
    productFlavors {
        mock {
            dimension "api"
            applicationIdSuffix ".mock"
            buildConfigField "boolean", "MOCK_API", "true"
        }
        prod {
            dimension "api"
            buildConfigField "boolean", "MOCK_API", "false"
        }
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    api 'androidx.appcompat:appcompat:1.8.0'
    api 'androidx.cardview:cardview:1.0.0'
    api 'com.google.android.material:material:1.14.0'
    api 'androidx.legacy:legacy-support-v4:1.0.0'
    api 'com.google.android.gms:play-services-maps:20.0.0'
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.okhttp3:okhttp:5.5.0'
    implementation "androidx.preference:preference-ktx:1.2.1"
    implementation 'com.google.android.gms:play-services-location:21.4.0'
    implementation 'pub.devrel:easypermissions:3.0.0'
    implementation 'androidx.activity:activity-ktx:1.13.0'
    implementation "androidx.core:core-ktx:1.19.0"
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'
}

private Integer generateVersionCode() {
    project.versionCode
}

private String generateVersionName() {
    String.format("0.%s", Integer.toString(generateVersionCode()))
}

private static String generateReleaseDate() {
    Date currentDate = new Date()
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd MMMM yyyy", Locale.getDefault())
    String currentDateFormatted = dateFormat.format(currentDate)

    currentDateFormatted
}
